config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      put :change
    end
  end

  devise_for :users

  get 'pages/home'
  
  get 'about' => 'pages#about'

  get 'test' => 'pages#test'

  root 'pages#home'

end

app/models/task.rb
class Task < ActiveRecord::Base
    validates :user_id, presence: true 
	validates :content, presence: true

    belongs_to :user

    auto_html_for :content do
        html_escape
		image
		youtube(width: '100%', height: 250 )
		link target: '_blank', rel: 'nofollow'
		simple_format
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    if current_user
  		redirect_to tasks_path
  	end
  end

  def about
  end

  def test
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]
  before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
#   @tasks = current_user.tasks
    @to_do = current_user.tasks.where(state: "to_do").order('created_at DESC')
    @doing = current_user.tasks.where(state: "doing").order('created_at DESC')
    @done = current_user.tasks.where(state: "done").order('created_at DESC')
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format| 
      format.html { redirect_to tasks_path, notice: "Task status successfully changed"}
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
            <p><i class="fa fa-circle-o-notch"></i>rDoo</p>
        <% end %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
             <% if current_user %>            
                <li class="test<% if params[:controller] == 'devise/registrations' %> active<% end %>"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                <li class="test<% if params[:controller] == 'devise/sessions' %> active<% end %>"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li class="test<% if params[:action] == 'about' %> active<% end %>"><%= link_to 'About', about_path %></li>
                <li class="test<% if params[:controller] == 'devise/sessions' %> active<% end %>"><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
        </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>rDoo</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
<% debug params %>
</body>
</html>

app/views/pages/_text.html.erb
<p>
    <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat doloremque blanditiis, autem, ullam quia ipsam possimus aperiam quas odio beatae perferendis ut consequatur optio aliquam, dolor tempora delectus fugit. Officiis.</span>
    <span>Numquam eius necessitatibus, rerum porro ipsum id dolorum quidem odit fugiat cum commodi odio amet recusandae ipsa, earum iure molestias officiis. Ipsum explicabo velit, voluptatibus, animi facere corporis optio consequatur!</span>
    <span>Quod reprehenderit consequuntur architecto est in sunt nam voluptatem. Quasi et aperiam temporibus blanditiis ut molestias consequatur aspernatur repellendus quaerat, dolorem praesentium illum vero impedit harum quis quia amet sunt.</span>
    <span>Nobis reprehenderit omnis quia dolores in officiis, eos, quod repellat sit. Officia ipsa magnam odit quos laboriosam commodi ipsam est, dolor dolores omnis id ipsum voluptas! Quos quia rem expedita!</span>
    <span>Mollitia deleniti ex unde a, sint recusandae, voluptatibus, laborum provident atque quia doloremque! Pariatur consequatur facilis, dignissimos vel dolorem, natus sequi animi a est quibusdam nobis tempora necessitatibus. Odio, possimus.</span>
</p>

app/views/pages/about.html.erb
<h1>About Us</h1>

<p>Information about us</p>

app/views/pages/home.html.erb
<div class="jumbotron">

    <h1><i class="fa fa-circle-o-notch"></i>rDoo</h1>

    <%= render 'text' %>

    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>

</div>

app/views/pages/test.html.erb
<h1>Test Page</h1>

<div class="row">
    <div class="col-md-4">
        <h1 class="text-center">ToDo</h1>
        <div class="panel panel-info">
            <div class="panel-heading">Todo</div>
            <div class="panel-body">Need to update this.</div>
            <div class="panel-footer text-center">doing</div>
        </div>
    </div>

    <div class="col-md-4">
        <h1 class="text-center">Doing</h1>
        <div class="panel panel-info">
            <div class="panel-heading">Doing</div>
            <div class="panel-body">Working on this right now</div>
            <div class="panel-footer text-center">change state</div>
        </div>
    </div>

    <div class="col-md-4">
        <h1 class="text-center">Done</h1>
        <div class="panel panel-info">
            <div class="panel-heading">Done</div>
            <div class="panel-body">Finally</div>
            <div class="panel-footer text-center">change state</div>
        </div>
    </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: {class: 'form-signin'}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :content, required: true, label: false, autofocus: true, placeholder: "Content" %>
    <%= f.button :submit, class: "btn btn-lg btn-primary btn-block" %>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id(task) %>" class="panel panel-info">
    <div class="panel-heading">
        <%= link_to edit_task_path(task) do %>
		    Created <%= time_ago_in_words(task.created_at) %> ago 
	    <% end %>
        <%= link_to 'X', task_path(task), method: :delete, data: {confirm: "Are you sure?"}, class: 'pull-right' %>
    </div>
    <div class="panel-body"><%= raw task.content_html %></div>
    <div class="panel-footer text-center">
        <div class="btn-group btn-group-justified">
            <% if task.state == 'doing' %>
                <%= link_to "<i class ='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "to_do"), method: :put, remote: true, class: "btn btn-info btn-md btn-block doing-todo"  %>
                <%= link_to "<i class ='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, remote: true, class: "btn btn-info btn-md btn-block doing-done"  %>
            <% elsif task.state == 'done' %>
                <%= link_to "<i class ='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "doing"), method: :put,remote: true, class: "btn btn-info btn-md btn-block done-doing"  %>
            <% else %>
                <%= link_to "<i class ='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "doing"),method: :put, remote: true, class: "btn btn-info btn-md btn-block todo-doing" %>
            <% end %>
        </div>
    </div>
</div>

app/views/tasks/change.js.erb
$('.todo-doing').bind('ajax:success', function() {
   $(this).closest('.panel-info').slideUp();
   $('.doing-panel').append("<%= escape_javascript render(@task) %>");
});

$('.doing-todo').bind('ajax:success', function() {
   $(this).closest('.panel-info').slideUp();
   $('.todo-panel').append("<%= escape_javascript render(@task) %>");
});

$('.doing-done').bind('ajax:success', function() {
   $(this).closest('.panel-info').slideUp();
   $('.done-panel').append("<%= escape_javascript render(@task) %>");
});

$('.done-doing').bind('ajax:success', function() {
   $(this).closest('.panel-info').slideUp();
   $('.doing-panel').append("<%= escape_javascript render(@task) %>");
});

app/views/tasks/edit.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @task, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1 class="text-center">Editing task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <%= link_to new_task_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Task
  <% end %>  
</div>


<div class="row">
    <div class="col-md-4">
        <h1 class="text-center">ToDo</h1>
        <div class="todo-panel">
            <%= render @to_do %>
        </div>
        
    </div>

    <div class="col-md-4">
        <h1 class="text-center">Doing</h1>
        <div class="doing-panel">
            <%= render @doing %>
        </div>        
    </div>

    <div class="col-md-4 done-panel">
        <h1 class="text-center">Done</h1>
        <div class="done-panel">
            <%= render @done %>
        </div>
        
    </div>
</div>

app/views/tasks/new.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1 class="text-center">New task</h1>
</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_task_path(@task), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show task</h1>
</div>

<dl class="dl-horizontal">
  <dt>Content:</dt>
  <dd><%= @task.content %></dd>
</dl>

<dl class="dl-horizontal">
  <dt>State:</dt>
  <dd><%= @task.state %></dd>
</dl>